##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Do Promote command
on:
  repository_dispatch:
    types:
      - promote-command

permissions:
  issues: write
  checks: read
  deployments: write
  contents: read
  packages: read
  statuses: write

jobs:
  promote:
    uses: .github/workflows/base/slash-on-promote.yml
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
