##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Chatops Agent
on:
  issue_comment:
    types:
      - created

permissions:
  issues: write
  contents: write
  packages: read
  statuses: write
  security-events: write

jobs:
  gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        if: ${{ !github.event.issue.pull_request }}
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commands: |
            deploy
            promote
            rebuild
          static-args: |
            author=${{ github.actor }}
            issue_number=${{ github.event.issue.number }}
            issue_repository=${{ github.repository }}
      - name: Slash Command Dispatch Pull-Request
        if: ${{ github.event.issue.pull_request }}
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commands: |
            approved
            approve
            lgtm
            cancel
            retry
          static-args: |
            author=${{ github.actor }}
            pull_request=true
            pull_request_number=${{ github.event.issue.number }}
          
